
trigger:
- main

jobs:
- job: BuildAndPush
  pool:
    vmImage: 'ubuntu-latest'
  steps:



  - script: docker build -t pipelines-javascript-docker:$(Build.BuildId) .
    displayName: 'Build Docker Image'
    env:
      DOCKER_BUILDKIT: 1

  - script: docker login -u $mdaziz -p $Clubca1920
    displayName: 'Docker Login'

  - script: docker tag pipelines-javascript-docker:$(Build.BuildId) mdaziz/pipelines-javascript-docker:latest
    displayName: 'Tag Docker Image'

  - script: docker push mdaziz/pipelines-javascript-docker:latest
    displayName: 'Push Docker Image'

  - script: docker build -t pipelines-javascript-docker:$(Build.BuildId) .
    displayName: 'Build Docker Image'
    env:
      DOCKER_BUILDKIT: 1
  - script: docker login -u $mdaziz -p $Clubca1920
    displayName: 'Docker Login'
  - script: docker tag pipelines-javascript-docker:$(Build.BuildId) mdaziz/pipelines-javascr$
    displayName: 'Tag Docker Image'
  - script: docker push mdaziz/pipelines-javascript-docker:latest
    displayName: 'Push Docker Image'

- job: DeployToAKS
  dependsOn: BuildAndPush
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: kubectl apply -f deployment.yaml
    displayName: 'Deploy to AKS'

